In [1]:
import numpy as np

In [2]:
list1 = [50,120,320,100,90,80,180,150,180,200]
list2 = [1,3,5,3,3,2,4,3,4,4]
list3 = [100,250,600,200,200,150,350,300,350,400]
array1 = np.array([[list1,
                   list2,
                   list3]])
print(array1)


[[[ 50 120 320 100  90  80 180 150 180 200]
  [  1   3   5   3   3   2   4   3   4   4]
  [100 250 600 200 200 150 350 300 350 400]]]


In [3]:
array1.shape

(1, 3, 10)

In [4]:
new_array = array1.transpose()

In [5]:
print(new_array)

[[[ 50]
  [  1]
  [100]]

 [[120]
  [  3]
  [250]]

 [[320]
  [  5]
  [600]]

 [[100]
  [  3]
  [200]]

 [[ 90]
  [  3]
  [200]]

 [[ 80]
  [  2]
  [150]]

 [[180]
  [  4]
  [350]]

 [[150]
  [  3]
  [300]]

 [[180]
  [  4]
  [350]]

 [[200]
  [  4]
  [400]]]


In [6]:
new_array.shape

(10, 3, 1)

In [39]:
#so new_array has 10 rows and 3 columns

In [ ]:
def matrix(rows,columns):
  last_array = 